services:

  vllm:
    image: vllm/vllm-openai:v0.26.0

    container_name: vllm

    volumes:
      - ../../data/vllm:/root/.cache/huggingface

    environment:
      - HF_TOKEN=${HF_TOKEN}

      - HTTP_PROXY=http://192.168.1.10:7890
      - HTTPS_PROXY=http://192.168.1.10:7890

      - http_proxy=http://192.168.1.10:7890
      - https_proxy=http://192.168.1.10:7890

      - NO_PROXY=localhost,127.0.0.1
      - no_proxy=localhost,127.0.0.1
      
      # - VLLM_USE_V1=0
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1

    ipc: host

    ports:
      - "8000:8000"

    command:
      - "Qwen/Qwen3-0.6B"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--dtype"
      - "auto"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities:
                - gpu

    networks:
      - ai-network


networks:

  ai-network:
    external: true
